// Main is a special name declaring an executable rather than a library.
package main

// Import declaration declares library packages referenced in this file.
import (
	"fmt" // A package in the Go standard library.
	"os"  // OS functions like working with the file system

	"github.com/sacarvy/VynaLab/src/numbers"
)

func main() {
	var current int;
	var inputBytes,err = os.ReadFile("./index.html");
	
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(numbers.Num);
	for current < len(inputBytes) {
		var currentWord =  string(inputBytes[current]);
		print(currentWord)
		if currentWord == "p" {
			fmt.Println(give(currentWord));
		}
		current++
	}
}

func give(arg string) string {
	switch arg {
		case "p":
			return "padding"
		case "m":
			return "margin"
		case "w":
			return "width"
		case "h":
			return "height"
		case "bg":
			return "background"
		default:
			return ""
	}
}

type CSSProperties struct {
	padding,margin,border property
}

type property struct {
	shortName, self, related string
	value []string
}

var Properties CSSProperties = CSSProperties{
	padding: padding,
	margin: margin,
	border: border,
}

var padding property = property{
	shortName: "p",
	self: "padding",
	related: "boxModel",
	value: []string{},
};

var margin property = property{
	shortName: "m",
	self: "margin",
	related: "boxModel",
	value: []string{},
};

var border property = property{
	shortName: "border",
	self: "border",
	related: "boxModel",
	value: []string{},
};
/*
//  Animation 
animation: ""
animationDelay: ""
animationDirection: ""
animationDuration: ""
animationFillMode: ""
animationIterationCount: ""
animationName: ""
animationPlayState: ""
animationTimeline: ""
animationTimingFunction: ""
webkitAnimation: ""
webkitAnimationDelay: ""
webkitAnimationDirection: ""
webkitAnimationDuration: ""
webkitAnimationFillMode: ""
webkitAnimationIterationCount: ""
webkitAnimationName: ""
webkitAnimationPlayState: ""
webkitAnimationTimingFunction: ""

// $Transition
willChange: ""
transition: ""
transitionDelay: ""
transitionDuration: ""
transitionProperty: ""
transitionTimingFunction: ""
webkitTransition: ""
webkitTransitionDelay: ""
webkitTransitionDuration: ""
webkitTransitionProperty: ""
webkitTransitionTimingFunction: ""

// $bg 
background: ""
backgroundAttachment: ""
backgroundBlendMode: ""
backgroundClip: ""
backgroundColor: ""
backgroundImage: ""
backgroundOrigin: ""
backgroundPosition: ""
backgroundPositionX: ""
backgroundPositionY: ""
backgroundRepeat: ""
backgroundRepeatX: ""
backgroundRepeatY: ""
backgroundSize: ""
webkitBackgroundClip: ""
webkitBackgroundOrigin: ""
webkitBackgroundSize: ""
// $boxModel
boxSizing: ""
width:""
height:""
maxBlockSize: ""
maxHeight: ""
maxInlineSize: ""
maxWidth: ""
minBlockSize: ""
minHeight: ""
minInlineSize: ""
minWidth: ""

// $p
padding: ""
paddingBlock: ""
paddingBlockEnd: ""
paddingBlockStart: ""
paddingBottom: ""
paddingInline: ""
paddingInlineEnd: ""
paddingInlineStart: ""
paddingLeft: ""
paddingRight: ""
paddingTop: ""
webkitPaddingAfter: ""
webkitPaddingBefore: ""
webkitPaddingEnd: ""
webkitPaddingStart: ""

// $border 
border: ""
borderBlock: ""
borderBlockColor: ""
borderBlockEnd: ""
borderBlockEndColor: ""
borderBlockEndStyle: ""
borderBlockEndWidth: ""
borderBlockStart: ""
borderBlockStartColor: ""
borderBlockStartStyle: ""
borderBlockStartWidth: ""
borderBlockStyle: ""
borderBlockWidth: ""
borderBottom: ""
borderBottomColor: ""
borderBottomLeftRadius: ""
borderBottomRightRadius: ""
borderBottomStyle: ""
borderBottomWidth: ""
borderCollapse: ""
borderColor: ""
borderEndEndRadius: ""
borderEndStartRadius: ""
borderImage: ""
borderImageOutset: ""
borderImageRepeat: ""
borderImageSlice: ""
borderImageSource: ""
borderImageWidth: ""
borderInline: ""
borderInlineColor: ""
borderInlineEnd: ""
borderInlineEndColor: ""
borderInlineEndStyle: ""
borderInlineEndWidth: ""
borderInlineStart: ""
borderInlineStartColor: ""
borderInlineStartStyle: ""
borderInlineStartWidth: ""
borderInlineStyle: ""
borderInlineWidth: ""
borderLeft: ""
borderLeftColor: ""
borderLeftStyle: ""
borderLeftWidth: ""
borderRadius: ""
borderRight: ""
borderRightColor: ""
borderRightStyle: ""
borderRightWidth: ""
borderSpacing: ""
borderStartEndRadius: ""
borderStartStartRadius: ""
borderStyle: ""
borderTop: ""
borderTopColor: ""
borderTopLeftRadius: ""
borderTopRightRadius: ""
borderTopStyle: ""
borderTopWidth: ""
borderWidth: ""
webkitBorderAfter: ""
webkitBorderAfterColor: ""
webkitBorderAfterStyle: ""
webkitBorderAfterWidth: ""
webkitBorderBefore: ""
webkitBorderBeforeColor: ""
webkitBorderBeforeStyle: ""
webkitBorderBeforeWidth: ""
webkitBorderBottomLeftRadius: ""
webkitBorderBottomRightRadius: ""
webkitBorderEnd: ""
webkitBorderEndColor: ""
webkitBorderEndStyle: ""
webkitBorderEndWidth: ""
webkitBorderHorizontalSpacing: ""
webkitBorderImage: ""
webkitBorderRadius: ""
webkitBorderStart: ""
webkitBorderStartColor: ""
webkitBorderStartStyle: ""
webkitBorderStartWidth: ""
webkitBorderTopLeftRadius: ""
webkitBorderTopRightRadius: ""
webkitBorderVerticalSpacing: ""

// $m 
margin: ""
marginBlock: ""
marginBlockEnd: ""
marginBlockStart: ""
marginBottom: ""
marginInline: ""
marginInlineEnd: ""
marginInlineStart: ""
marginLeft: ""
marginRight: ""
marginTop: ""
webkitMarginAfter: ""
webkitMarginBefore: ""
webkitMarginEnd: ""
webkitMarginStart: ""

// Positioning 
position:""
top:""
left:""
right:""
bottom:""

// $flex
flex: ""
flexBasis: ""
flexDirection: ""
flexFlow: ""
flexGrow: ""
flexShrink: ""
flexWrap: ""
alignContent: ""
alignItems: ""
alignSelf: ""
justifyContent: ""
justifyItems: ""
justifySelf: ""

// Typography ---------------------------------------------------------------
color: ""
font: ""
fontDisplay: ""
fontFamily: ""
fontFeatureSettings: ""
fontKerning: ""
fontOpticalSizing: ""
fontSize: ""
fontStretch: ""
fontStyle: ""
fontVariant: ""
fontVariantCaps: ""
fontVariantEastAsian: ""
fontVariantLigatures: ""
fontVariantNumeric: ""
fontVariationSettings: ""
fontWeight: ""
letterSpacing: ""
lineHeight: ""
textAlign: ""
textAlignLast: ""
textAnchor: ""
textCombineUpright: ""
textDecoration: ""
textDecorationColor: ""
textDecorationLine: ""
textDecorationSkipInk: ""
textDecorationStyle: ""
textDecorationThickness: ""
textIndent: ""
textJustify: ""
textOrientation: ""
textOverflow: ""
textRendering: ""
textShadow: ""
textSizeAdjust: ""
textTransform: ""
textUnderlineOffset: ""
textUnderlinePosition: ""
wordBreak: ""
wordSpacing: ""
wordWrap: ""
writingMode: ""

accentColor: ""
additiveSymbols: ""
alignmentBaseline: ""
all: ""
appearance: ""
ascentOverride: ""
aspectRatio: ""
backdropFilter: ""
backfaceVisibility: ""
baselineShift: ""
blockSize: ""
boxShadow: ""
breakAfter: ""
breakBefore: ""
breakInside: ""
bufferedRendering: ""
captionSide: ""
caretColor: ""
clear: ""
clip: ""
clipPath: ""
clipRule: ""
columnCount: ""
columnFill: ""
columnGap: ""
columnRule: ""
columnRuleColor: ""
columnRuleStyle: ""
columnRuleWidth: ""
columnSpan: ""
columnWidth: ""
columns: ""
contain: ""
containIntrinsicSize: ""
content: ""
contentVisibility: ""
counterIncrement: ""
counterReset: ""
counterSet: ""
cssFloat: ""
cssText: ""
cursor: ""
cx: ""
cy: ""
d: ""
descentOverride: ""
direction: ""
display: ""
dominantBaseline: ""
emptyCells: ""
end: ""
fallback: ""
fill: ""
fillOpacity: ""
fillRule: ""
filter: ""
float: ""
floodColor: ""
floodOpacity: ""
forcedColorAdjust: ""
gap: ""
grid: ""
gridArea: ""
gridAutoColumns: ""
gridAutoFlow: ""
gridAutoRows: ""
gridColumn: ""
gridColumnEnd: ""
gridColumnGap: ""
gridColumnStart: ""
gridGap: ""
gridRow: ""
gridRowEnd: ""
gridRowGap: ""
gridRowStart: ""
gridTemplate: ""
gridTemplateAreas: ""
gridTemplateColumns: ""
gridTemplateRows: ""
hyphens: ""
imageOrientation: ""
imageRendering: ""
inherits: ""
initialValue: ""
inlineSize: ""
inset: ""
insetBlock: ""
insetBlockEnd: ""
insetBlockStart: ""
insetInline: ""
insetInlineEnd: ""
insetInlineStart: ""
isolation: ""
length: 0
lightingColor: ""
lineBreak: ""
lineGapOverride: ""
lineHeightStep: ""
listStyle: ""
listStyleImage: ""
listStylePosition: ""
listStyleType: ""
marker: ""
markerEnd: ""
markerMid: ""
markerStart: ""
mask: ""
maskType: ""
mathDepth: ""
mathShift: ""
mathStyle: ""
mixBlendMode: ""
negative: ""
objectFit: ""
objectPosition: ""
offset: ""
offsetAnchor: ""
offsetDistance: ""
offsetPath: ""
offsetPosition: ""
offsetRotate: ""
opacity: ""
order: ""
orientation: ""
orphans: ""
outline: ""
outlineColor: ""
outlineOffset: ""
outlineStyle: ""
outlineWidth: ""
overflow: ""
overflowAnchor: ""
overflowClipMargin: ""
overflowWrap: ""
overflowX: ""
overflowY: ""
overscrollBehavior: ""
overscrollBehaviorBlock: ""
overscrollBehaviorInline: ""
overscrollBehaviorX: ""
overscrollBehaviorY: ""
pad: ""
page: ""
pageBreakAfter: ""
pageBreakBefore: ""
pageBreakInside: ""
pageOrientation: ""
paintOrder: ""
parentRule: null
perspective: ""
perspectiveOrigin: ""
placeContent: ""
placeItems: ""
placeSelf: ""
pointerEvents: ""
position: ""
prefix: ""
quotes: ""
r: ""
range: ""
resize: ""
right: ""
rotate: ""
rowGap: ""
rubyPosition: ""
rx: ""
ry: ""
scale: ""
scrollBehavior: ""
scrollMargin: ""
scrollMarginBlock: ""
scrollMarginBlockEnd: ""
scrollMarginBlockStart: ""
scrollMarginBottom: ""
scrollMarginInline: ""
scrollMarginInlineEnd: ""
scrollMarginInlineStart: ""
scrollMarginLeft: ""
scrollMarginRight: ""
scrollMarginTop: ""
scrollPadding: ""
scrollPaddingBlock: ""
scrollPaddingBlockEnd: ""
scrollPaddingBlockStart: ""
scrollPaddingBottom: ""
scrollPaddingInline: ""
scrollPaddingInlineEnd: ""
scrollPaddingInlineStart: ""
scrollPaddingLeft: ""
scrollPaddingRight: ""
scrollPaddingTop: ""
scrollSnapAlign: ""
scrollSnapStop: ""
scrollSnapType: ""
scrollbarGutter: ""
shapeImageThreshold: ""
shapeMargin: ""
shapeOutside: ""
shapeRendering: ""
size: ""
sizeAdjust: ""
source: ""
speak: ""
speakAs: ""
src: ""
start: ""
stopColor: ""
stopOpacity: ""
stroke: ""
strokeDasharray: ""
strokeDashoffset: ""
strokeLinecap: ""
strokeLinejoin: ""
strokeMiterlimit: ""
strokeOpacity: ""
strokeWidth: ""
suffix: ""
symbols: ""
syntax: ""
system: ""
tabSize: ""
tableLayout: ""
timeRange: ""
touchAction: ""
transform: ""
transformBox: ""
transformOrigin: ""
transformStyle: ""
transition: ""
transitionDelay: ""
transitionDuration: ""
transitionProperty: ""
transitionTimingFunction: ""
translate: ""
unicodeBidi: ""
unicodeRange: ""
userSelect: ""
userZoom: ""
vectorEffect: ""
verticalAlign: ""
visibility: ""
webkitAlignContent: ""
webkitAlignItems: ""
webkitAlignSelf: ""
webkitAppRegion: ""
webkitAppearance: ""
webkitBackfaceVisibility: ""
webkitBackgroundClip: ""
webkitBackgroundOrigin: ""
webkitBackgroundSize: ""
webkitBoxAlign: ""
webkitBoxDecorationBreak: ""
webkitBoxDirection: ""
webkitBoxFlex: ""
webkitBoxOrdinalGroup: ""
webkitBoxOrient: ""
webkitBoxPack: ""
webkitBoxReflect: ""
webkitBoxShadow: ""
webkitBoxSizing: ""
webkitClipPath: ""
webkitColumnBreakAfter: ""
webkitColumnBreakBefore: ""
webkitColumnBreakInside: ""
webkitColumnCount: ""
webkitColumnGap: ""
webkitColumnRule: ""
webkitColumnRuleColor: ""
webkitColumnRuleStyle: ""
webkitColumnRuleWidth: ""
webkitColumnSpan: ""
webkitColumnWidth: ""
webkitColumns: ""
webkitFilter: ""
webkitFlex: ""
webkitFlexBasis: ""
webkitFlexDirection: ""
webkitFlexFlow: ""
webkitFlexGrow: ""
webkitFlexShrink: ""
webkitFlexWrap: ""
webkitHighlight: ""
webkitHyphenateCharacter: ""
webkitJustifyContent: ""
webkitLineBreak: ""
webkitLineClamp: ""
webkitLocale: ""
webkitLogicalHeight: ""
webkitLogicalWidth: ""
webkitMarginAfter: ""
webkitMarginBefore: ""
webkitMarginEnd: ""
webkitMarginStart: ""
webkitMask: ""
webkitMaskBoxImage: ""
webkitMaskBoxImageOutset: ""
webkitMaskBoxImageRepeat: ""
webkitMaskBoxImageSlice: ""
webkitMaskBoxImageSource: ""
webkitMaskBoxImageWidth: ""
webkitMaskClip: ""
webkitMaskComposite: ""
webkitMaskImage: ""
webkitMaskOrigin: ""
webkitMaskPosition: ""
webkitMaskPositionX: ""
webkitMaskPositionY: ""
webkitMaskRepeat: ""
webkitMaskRepeatX: ""
webkitMaskRepeatY: ""
webkitMaskSize: ""
webkitMaxLogicalHeight: ""
webkitMaxLogicalWidth: ""
webkitMinLogicalHeight: ""
webkitMinLogicalWidth: ""
webkitOpacity: ""
webkitOrder: ""
webkitPerspective: ""
webkitPerspectiveOrigin: ""
webkitPerspectiveOriginX: ""
webkitPerspectiveOriginY: ""
webkitPrintColorAdjust: ""
webkitRtlOrdering: ""
webkitRubyPosition: ""
webkitShapeImageThreshold: ""
webkitShapeMargin: ""
webkitShapeOutside: ""
webkitTapHighlightColor: ""
webkitTextCombine: ""
webkitTextDecorationsInEffect: ""
webkitTextEmphasis: ""
webkitTextEmphasisColor: ""
webkitTextEmphasisPosition: ""
webkitTextEmphasisStyle: ""
webkitTextFillColor: ""
webkitTextOrientation: ""
webkitTextSecurity: ""
webkitTextSizeAdjust: ""
webkitTextStroke: ""
webkitTextStrokeColor: ""
webkitTextStrokeWidth: ""
webkitTransform: ""
webkitTransformOrigin: ""
webkitTransformOriginX: ""
webkitTransformOriginY: ""
webkitTransformOriginZ: ""
webkitTransformStyle: ""
webkitUserDrag: ""
webkitUserModify: ""
webkitUserSelect: ""
webkitWritingMode: ""
whiteSpace: ""
widows: ""
x: ""
y: ""
zIndex: ""
zoom: ""
epubCaptionSide: <unreadable>
epubTextCombine: <unreadable>
epubTextEmphasis: <unreadable>
epubTextEmphasisColor: <unreadable>
epubTextEmphasisStyle: <unreadable>
epubTextOrientation: <unreadable>
epubTextTransform: <unreadable>
epubWordBreak: <unreadable>
epubWritingMode: <unreadable>
*/